<?php
/**
 * Created by PhpStorm.
 * User: Debam
 * Date: 12/18/17
 * Time: 10:47 AM
 */

namespace app\models;


use yii\db\ActiveRecord;

class Users extends ActiveRecord
{
    public static function tableName()
    {
        return 'users'; // TODO: Change the autogenerated stub
    }

    public static function getFullName($u){
        $user = self::find()
            ->select(['fullname'])
            ->where(['username'=>$u])
            ->asArray()
            ->one();

        //SELECT fullname FROM users WHERE username ='$u';

        return $user['fullname'];
    }

    public static function validatePassword($u, $p){
        $user = self::find()
            ->andWhere(['username'=>$u])
            ->andWhere(['password'=>$p])
            ->asArray()
            ->one();

//        SELECT * FROM users WHERE 'username' = $u AND 'password'=$p;

        if(!empty($user)){
            return true;
        } else {
            return false;
        }
    }


}